// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDulLbczowx6TY-qKaRSNpfUjfEh5DuQ3w',
    appId: '1:667454708400:web:7e13db877c43654e9e7975',
    messagingSenderId: '667454708400',
    projectId: 'tyla-78c36',
    authDomain: 'tyla-78c36.firebaseapp.com',
    storageBucket: 'tyla-78c36.appspot.com',
    measurementId: 'G-HBFNQJ8K75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV8nb5MmEOT-nEd6WrNSx5RuTefsfdWyc',
    appId: '1:667454708400:android:fc2be09f4d7df74e9e7975',
    messagingSenderId: '667454708400',
    projectId: 'tyla-78c36',
    storageBucket: 'tyla-78c36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG6ouwmb62oEZLQa5GUS6xOWR6Pct_2mo',
    appId: '1:667454708400:ios:d584d6803cdbc6139e7975',
    messagingSenderId: '667454708400',
    projectId: 'tyla-78c36',
    storageBucket: 'tyla-78c36.appspot.com',
    iosBundleId: 'com.example.tyla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG6ouwmb62oEZLQa5GUS6xOWR6Pct_2mo',
    appId: '1:667454708400:ios:0c67e4c14f1cdacb9e7975',
    messagingSenderId: '667454708400',
    projectId: 'tyla-78c36',
    storageBucket: 'tyla-78c36.appspot.com',
    iosBundleId: 'com.example.tyla.RunnerTests',
  );
}
